version: "3.9"
services:

  # denji
  denji-db:
    image: postgres
    restart: no
    environment:
      POSTGRES_DB: denji
      POSTGRES_USER: denji
      POSTGRES_PASSWORD: denji
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "20012:5432"
    volumes:
      - denji-db:/var/lib/postgresql/data

  denji-migrator:
    image: yaiam/denji:5f018c5db44ed2b0b9bb1a7bed3830c22b82c538
    depends_on:
      denji-db:
        condition: service_healthy
    restart: no
    environment:
      MODE: MIGRATOR
      Database__ConnectionString: "Host=denji-db;Port=5432;Username=denji;Password=denji;Database=denji;"
    volumes:
      - /Users/dk/.aspnet/https/localhost.pfx:/https/localhost.pfx

  denji:
    image: yaiam/denji:5f018c5db44ed2b0b9bb1a7bed3830c22b82c538
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: localhost
      ASPNETCORE_URLS: "http://+;https://+"
      Cors__Origins__0: "http://localhost:20020"
      Cosmo__BaseUrl: "http://localhost:20020"
    ports:
      - "20000:443"
    volumes:
      - /Users/dk/.aspnet/https/localhost.pfx:/https/localhost.pfx

  # power
  power-db:
    image: postgres
    restart: no
    environment:
      POSTGRES_DB: power
      POSTGRES_USER: power
      POSTGRES_PASSWORD: power
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "20012:5432"
    volumes:
      - identity:/var/lib/postgresql/data

  power-migrator:
    image: yaiam/power:2410621e73b7e66bbc47aa7a0c9bed6a8b95e3d1
    depends_on:
      power-db:
        condition: service_healthy
    restart: no
    environment:
      MODE: MIGRATOR
      Database__ConnectionString: "Host=power-db;Port=5432;Username=power;Password=power;Database=power;"
    volumes:
      - /Users/dk/.aspnet/https/localhost.pfx:/https/localhost.pfx

  power:
    image: yaiam/power:2410621e73b7e66bbc47aa7a0c9bed6a8b95e3d1
    depends_on:
      identity-migrator:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: localhost
      ASPNETCORE_URLS: "http://+;https://+"
      Auth__BaseUrl: "http://denji:80"
      Cors__Origins__0: "http://localhost:20020"
      Database__ConnectionString: "Host=power-db;Port=5432;Username=power;Password=power;Database=power;"
      MODE: WEB
    ports:
      - "20010:443"
    volumes:
      - /Users/dk/.aspnet/https/localhost.pfx:/https/localhost.pfx

  # cosmo
  cosmo:
    image: yaiam/cosmo:278d78e8fc090c5d3e6b445e533cd4e65ed083ac
    environment:
      NEXT_PUBLIC_POWER_PUBLIC_BASE_URL: "https://localhost:20010"
      NEXT_PUBLIC_DENJI_PUBLIC_BASE_URL: "https://localhost:20000"
    ports:
      - "20020:3000"

  # beam
  beam:
    image: yaiam/beam:69ca7ce45ce32d4c8219b9b3fdd347741a787b9d
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: localhost
      ASPNETCORE_URLS: "http://+;https://+"
      Auth__BaseUrl: "http://denji:80"
      Auth__IssuerUrl__0: "https://denji:80"
      Auth__IssuerUrl__1: "https://localhost:20000"
    ports:
      - "20030:443"
    volumes:
      - /Users/dk/.aspnet/https/localhost.pfx:/https/localhost.pfx

volumes:
  denji-db:
  power-db: